language: swift
osx_image: xcode11.3
xcode_workspace: FetchUser.xcworkspace
xcode_scheme: FetchUser
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
podfile: FetchUser/Podfile
cache: cocoapods
branches:
  only:
    - master

before_install:
  - pod install
  - gem install travis -v 1.8.9 --no-document
jobs:
  include:
    - stage: XCTest
      script:
        - fastlane scan -s FetchUserTests
    - stage: XCUITest
      script:
        - fastlane scan -s FetchUserUITests
