os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -workspace /Users/akifdemirezen/Desktop/FetchUser/FetchUser.xcworkspace -scheme "FetchUser" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.3,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNIGN_REQUIRED=NO
