language: swift
osx_image: xcode11.3
notifications:
  email: false
branches:
  only:
    - master

before_install:
  - sudo gem install fastlane 

jobs:
  include:
    - stage: FetchUser
      script:
        - ./Pods/FetchUser/swiftlint --reporter junit

    - stage: XCTest
      script:
        - fastlane scan -s FetchUserTests

    - stage: XCTest
      script:
        - fastlane scan -s SFetchUserUITests
