jobs:
  include:
    - name: Run Unit Tests (iOS, Xcode 10.3)
      osx_image: xcode10.3
      script: FetchUser.xcworkspace -s "FetchUser" -d "OS=13.3,name=iPhone X" -d "OS=11.4,name=iPhone X" -d "OS=13.3,name=iPhone X"
